// <auto-generated />
using GFSUploadAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GFSUploadAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200312132731_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("GFSUploadAPI.Models.AccountBookKeeping", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("CounterAccountIDKT")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<string>("IDKT")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalIDKT")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AccountBookKeeping");
                });
#pragma warning restore 612, 618
        }
    }
}
